apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: costsavers.costsaver.leapwork
spec:
  group: costsaver.leapwork
  names:
    kind: CostSaver
    listKind: CostSaverList
    plural: costsavers
    singular: costsaver
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: The cost saver status.
            properties:
              trackedNamespaces:
                description: The tracked namespaces.
                items:
                  description: The tracked namespace details.
                  properties:
                    name:
                      description: The name of the namespace.
                      type: string
                    createdAt:
                      description: The creation timestamp of the namespace.
                      format: date-time
                      type: string
                    lifetime:
                      description: The lifetime of the namespace.
                      type: string
                    expiresAt:
                      description: The expiration date of the namespace.
                      format: date-time
                      type: string
                  type: object
                type: array
            type: object
          spec:
            description: The cost saver specification.
            properties:
              namespaceLabel:
                description: The namespace label to track.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}