global using Xunit;
global using k8s.Models;
global using KubeOps.Operator.Events;
global using NSubstitute;
global using AutoFixture;
global using AutoFixture.Xunit2;
global using CostSaver.Extensions;
global using KubeOps.KubernetesClient;
global using Microsoft.Extensions.Logging;
global using FluentAssertions;
global using CostSaverEntity = CostSaver.Entities.CostSaver;
